### ISSUE TITLE
Multiple WP on same host

### ISSUE THREAD

**Issue by vic3lord** [brint/wordpress-cookbook#33]
You can't use this cookbook as a wrapper cookbook and it can't be used for multiple installs on the same host as it uses attributes to install.

There should be LWRPs to install wordpress site

**Comment by brint** [comment]
I've put up a draft in the [lib branch](https://github.com/brint/wordpress-cookbook/tree/lib).  It is following the convention of most of the community cookbooks that are turning more into libraries.

Sample usage for installing two sites from tarball on the same machine:

``` ruby
# The following installs the latest version of WordPress to /var/www/wordpress
wordpress_install 'default' do
  action :create
end

# Here's a second installation to a different path that installs a different version 
# of WordPress. Additionally the user/group settings are different since you 
# may have different users that need permissions/access to different sites.
wordpress_install 'example2.com' do
  install_method 'tarball'  # this is the default install_method
  install_path '/var/www/example2.com'
  version '3.9.3'
  owner 'www-data'
  group 'www-data'
  action :create
end
```

Another installation option is via unauthenticated git, inspired by #51.

``` Ruby
# Defaults to master ref and syncs to /var/www/wordpress
wordpress_install 'default' do
  install_method 'git'
  action :create
end

wordpress_install 'example2.com' do
  install_method 'git'
  install_path '/var/www/example2.com'
  reference '3.9.3'
  owner 'www-data'
  group 'www-data'
  action :create
end
```

I've put in some basic tests as well. Once I change out how WordPress is installed in the `wordpress::app`, I'll merge it into `master` and cut a new release. This sounds like it should fit what you were looking for.

**Comment by dmyers** [comment]
:+1:
